### ISSUE TITLE
[Failed mission]Corpselice Spawnlings

### ISSUE THREAD

**Issue by theruan** [Gaboros/VenturePlan#10]
If I understood it right we have to replace the data that is shown in the interface in the correct skill(per wowhead), if so:
Old/new
Removed data i had wrongly stated.

**Comment by theruan** [comment]
Srry, just read the reddit post again and found the multiplier thing, with that the original data should be correct, but most of my missions still fail, how do I get the log for these missions?

**Comment by Gaboros** [comment]
If you have log/screenshot of the mission please share and we can verify if it's correct or not. Thanks!

**Comment by Gaboros** [comment]
Log from Knut.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795408/mission.txt)

**Comment by Gaboros** [comment]
Log from Lompak.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795426/mission.txt)

**Comment by MMOSimca** [comment]
No new spells in this mission either - 11, 94, 199, 200, 201, 302.

**Comment by MMOSimca** [comment]
Spotted an error in SpellID 200, not sure if a new change or not. target is 0, but it should be "enemy-front" (it's a swipe).

**Comment by MMOSimca** [comment]
Checked data files for GarrAutoSpellEffect from Patch 9.0.5 and 9.1.0. There were two small changes in Patch 9.1.0 that weren't additions - one to SpellID 107 and one to SpellID 200. So this isn't a previous data error, it's a patch change to fix a Blizzard bug.

**Comment by Legenjerry** [comment]
In the logs it indeed shows that spell 200 hits slots 2, 3, and 4 every cast, and only defaults to slots 0 or 1 if the others are dead.
So it should be:
[200]={type="aura", target="enemy-front", damageATK=100, modDamageDealt=-50, duration=1},

**Comment by MMOSimca** [comment]
Should be fixed by #42.
