### ISSUE TITLE
Create Tags and Releases for Addon Managers

### ISSUE THREAD

**Issue by PascaleBeier** [Gaboros/VenturePlan#11]
Hey there,

thanks for chiming in and taking care of Venture Plan.

For easy usage with Addon Managers like Ajour, we need to create according GitHub Releases and Tags.

I can set this up for you, if you like me to! We would package the Releases so that they contain the correct Folder structure.

**Comment by linaori** [comment]
Same goes for WowUp, would be awesome to be able to quickly install this

**Comment by Gaboros** [comment]
Thank you for your suggestion! I have created a pre-release. Tested with WowUp and for me it's seems ok. Let me know if it's not. :)

**Comment by stevietv** [comment]
its not working correctly with WowUp - in the zip file you packaged you first need to have a folder `Venture Plan` - having the addon directly in the zip doesn't allow it to extract properly. All I ended up with was a loose libs folder.

**Comment by Gaboros** [comment]
Thanks! I have fixed it. :)

**Comment by stevietv** [comment]
> Thanks! I have fixed it. :)

yep, its working nicely now 👍🏻

**Comment by PascaleBeier** [comment]
works great with ajour as well, thanks 👍
