### ISSUE TITLE
Verification for Tainted Bite & Regurgitated Meal

### ISSUE THREAD

**Issue by jscharnitzke** [Gaboros/VenturePlan#15]
Images attached. If it's easier, feel free to make me a contributor, and I'll open a PR.
![341 - Tainted Bite](https://user-images.githubusercontent.com/2000659/125101869-8a4a4380-e08f-11eb-8ca0-386a6e5c07cd.png)
![342 - Regurgitated Meal](https://user-images.githubusercontent.com/2000659/125101876-8c140700-e08f-11eb-8475-8f5abb0d7ce8.png)

**Comment by Gaboros** [comment]
Thanks! I have added it! https://github.com/Gaboros/VenturePlan/commit/edc6b2beb37239f924f2b73bc40b5748871edf21

By the way you can open a PR without being a contributor. I invite the people as contributor after submitting a PR. Included your name as well. :)
