### ISSUE TITLE
Possible to add a release so updates will be possible via CurseBreaker?

### ISSUE THREAD

**Issue by alcaras** [Gaboros/VenturePlan#16]
Would it be possible to add a packaged release so Cursebreaker (addon updater) can pull updates?

```
CB> install https://github.com/Gaboros/VenturePlan
1/1 | ----------------------------------------------------------------------------------------- |
┌────────┬───────────────┬─────────┐
│ Status │ Name / Author │ Version │
├────────┼───────────────┼─────────┤
└────────┴───────────────┴─────────┘
RuntimeError: Failed to parse addon data: https://github.com/Gaboros/VenturePlan
This integration supports only the projects that provide packaged releases.
```

Packaging can be done via: https://github.com/BigWigsMods/packager

**Comment by Gaboros** [comment]
There is a release. I tried it working with WowUp. Don't know about Cursebreaker.

**Comment by klistak** [comment]
CurseBreaker is nice little tool for addon updates and so on. Looks like there must be package so CurseBreaker will be able to work with it.
https://github.com/AcidWeb/CurseBreaker/issues/171

**Comment by alcaras** [comment]
Thank you! I needed to switch CB to see the beta channel.

**Comment by Enigma-TL** [comment]
How do you update it with Wowup? Mine is 15 days old and I can not find a "install by url" listed any where?  Am I mission something?  It came from WowupHub and was put out by foxlit. Is that this version?

**Comment by sehra** [comment]
Works fine with WowUp, but you need to remove the old one and use "Install from URL", entering the address of this repository.

**Comment by Enigma-TL** [comment]
> Works fine with WowUp, but you need to remove the old VenturePlan and use "Install from URL", entering the address of this repository.

What directory does it install to under addons?  I deleted the old one and added via the URL, claims its installed but do not see a directory under the addons?

**Comment by alcaras** [comment]
Updated the original issue with details as to the error and how to package releases. Thank you!

**Comment by sehra** [comment]
Looks like the problem is that the current releases are marked a pre-release, CurseBreaker will not pick those up.
