### ISSUE TITLE
[Failed mission]Customary Shakedown

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#24]
Find this one in logs of Shai.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6794841/mission.txt)

**Comment by Gaboros** [comment]
Another log from SubNick. 
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795114/mission.txt)

**Comment by Gaboros** [comment]
Another log from Knut.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795402/mission.txt)

**Comment by Legenjerry** [comment]
The log from SubNick is for Learn from the Master (in French)
All 3 logs are the result of incorrectly simmed enemy autoattack style. It should be resolved in v5.3-beta.
