### ISSUE TITLE
[Failed mission]Learn from the Master

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#30]
Find this one in logs of Priëllaya.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6794917/mission.txt)

**Comment by theruan** [comment]
Same mission, log in english
[log.txt](https://github.com/Gaboros/VenturePlan/files/6796010/log.txt)

**Comment by Legenjerry** [comment]
This is the result of incorrectly simmed enemy autoattack style. It should be resolved in v5.3-beta.
