### ISSUE TITLE
[Failed mission]A Few Too Many

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#32]
Find this one in logs of Lompak.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795328/mission.txt)

**Comment by Gaboros** [comment]
An another log from Knut.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795406/mission.txt)

**Comment by Gaboros** [comment]
Another log from Fanghorn.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795637/mission.txt)

**Comment by Legenjerry** [comment]
This is the result of incorrectly simmed enemy autoattack style. It should be resolved in v5.3-beta.
