### ISSUE TITLE
[Failed mission]On Wings of Ferocity

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#35]
Logs from Pokey.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795417/mission.txt)

**Comment by Gaboros** [comment]
Another log from Jarosław Kaczyński.
[mission.txt](https://github.com/Gaboros/VenturePlan/files/6795638/mission.txt)

**Comment by Legenjerry** [comment]
This is the result of incorrectly simmed enemy autoattack style. It should be resolved in v5.3-beta.
