### ISSUE TITLE
Spell 107 and 122

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#43]
Got this one from Reddit:

```Hey,

I don't have a github account, but I wanted to let you know that I found a few more broken spells for VenturePlan. 
These seems like they were bugged initially in game. I remember 107 behaving the way that it is described currently, 
but seems to be fixed - watched a battle play out yesterday. Haven't seen a battle with 122, but saw the tooltip in 
one my missions, so it wouldn't hurt to have it properly set, since the damage is so low. For 107 you also 
need to remove a line in Util.lua, in the overdesc table.

[107]={ {type="nuke", target=0, damageATK=150}, {type="aura", target=0, plusDamageTakenATK=50, duration=3}, },

[122]={type="aura", target="random-enemy", duration=3, damageATK=10},

Cheers, Berry

**Comment by Gaboros** [comment]
122
Description:  Chaos and fire! This attack deals 55 Fire damage over three turns to a random enemy.
Creature damage:  184
Compared with for example https://www.wowhead.com/adventure-combatant-ability/anima-flame-259 this should be:
[122]={type="aura", target="random-enemy", duration=0, echo=3, noFirstTick=true, damageATK=30},

No logs for107.

**Comment by MMOSimca** [comment]
Should both be fixed by #42.

**Comment by zealvurte** [comment]
[log-2186.txt](https://github.com/Gaboros/VenturePlan/files/6805599/log-2186.txt)
I've just checked this novel log for mission 2186, which has spell 122. The spell is never cast in the log, and now that I've implemented a trace on sim and made it so I can replay reports against the sim at will, I'm able to verify this should have stayed as `[122]={type="nop"}`.

**Comment by MMOSimca** [comment]
I see why this is broken. It's a Blizzard mistake. This is what my spreadsheet outputs for 122:
>[122]={type="aura", target="random-enemy", duration=0, period=3, damageATK=30}, --Humorous Flame
This is what it outputs for the similar spell 259
>[259]={type="aura", target=0, duration=3, period=3, damageATK=30}, --Anima Flame

Turns out, duration=0 on a DoT aura means it does nothing. Who'd a thunk? GJ Blizz.

**Comment by zealvurte** [comment]
Well, currently it is using `echo=3`, and those echos were what the sim was casting when it shouldn't, so maybe just changing it to yours (`period=3`) would work too?

**Comment by MMOSimca** [comment]
I'd honestly rather change it to nop again and leave a note, just in case. Committed into the latest PR - #55.
