### ISSUE TITLE
Restore overrides for enemy autoattacks, while supporting fallback to specified ones

### ISSUE THREAD

**Issue by zealvurte** [Gaboros/VenturePlan#44]
As mentioned on discord, I think it would be better to still have the overrides available for enemies where still required; however, because the original code used the first spell ID instead of the auto attack ID, it was lacking a good fallback to the specified value and relied only on the role, leading to more overrides than required.

Best of both worlds would be the below:
vs.lua:415
Change:
```lua
		return (a1 or a2 or (role == 1 or role == 5) and 0 or 1) == 0 and 11 or 15
```
To:
```lua
		return (a1 or a2 or (firstSpell == 11 or role == 1 or role == 5) and 0 or 1) == 0 and 11 or 15
```

vs.lua:1349-1351
Change:
```lua
		local aa = e.autoCombatAutoAttack and e.autoCombatAutoAttack.autoCombatSpellID
		--local aa_old = VS:GetAutoAttack(e.role, rf.slot, mid, sa and sa[1] and sa[1].autoCombatSpellID)
		--print("slot="..tostring(e.boardIndex)..",old="..tostring(aa_old)..",new="..tostring(aa))
```
To:
```lua
		local aa = VS:GetAutoAttack(e.role, rf.slot, mid, e.autoCombatAutoAttack and e.autoCombatAutoAttack.autoCombatSpellID)
```

Someone can then go through and verify which values in `overrideAA` are no longer needed.

**Comment by zealvurte** [comment]
From a quick check, after making this change:
- e5d7aaa206cdfe6785d0e60173d35742eb3f2a88 `[409]` can be removed (will already be 11)
- f7f9c3c613d5a36d23eae7a556940518850c2f46 `[1309]` can be removed (will already be 11)

**Comment by Gaboros** [comment]
> From a quick check, after making this change:
> 
> * [e5d7aaa](https://github.com/Gaboros/VenturePlan/commit/e5d7aaa206cdfe6785d0e60173d35742eb3f2a88) `[409]` can be removed (will already be 11)
> * [f7f9c3c](https://github.com/Gaboros/VenturePlan/commit/f7f9c3c613d5a36d23eae7a556940518850c2f46) `[1309]` can be removed (will already be 11)

I'm not sure. They are followers and they don't have autoCombatSpellID. I think for followers the only way is using the overrides.

**Comment by zealvurte** [comment]
This change effects both enemies and allies, as even allies relied on using the roles rather than the first spell ID.

> * [e5d7aaa](https://github.com/Gaboros/VenturePlan/commit/e5d7aaa206cdfe6785d0e60173d35742eb3f2a88) `[409]` can be removed (will already be 11)

This was `[409]=1`, previously, because Groonemook's first spell ID 15, but the reliance on roles made it 11. In 9.1, the first spell ID was changed to 11, so the override isn't needed at all now.

> * [f7f9c3c](https://github.com/Gaboros/VenturePlan/commit/f7f9c3c613d5a36d23eae7a556940518850c2f46) `[1309]` can be removed (will already be 11)

This one has a first spell ID of 11 already, so it will use that now instead of relying on the role (which was 4, so was incorrectly resulting in 15).

**Comment by Gaboros** [comment]
> This one has a first spell ID of 11 already, so it will use that now instead of relying on the role (which was 4, so was incorrectly resulting in 15).

Yes, it's redundant, you are right.

>This was [409]=1 previously, because Groonoomcrooek's first spell ID was 15, but the reliance on roles would have made it 11. In 9.1, the first spell ID was changed to 11, so the override isn't needed at all now.

I found this for Groonoomcrooek in the logs. 
```"0x0000000021701693": {
            "spells": [{
                "description": "Groonoomcrooek's branches lash in the wind, dealing 54 Nature damage to all enemies in a line.",
                "autoCombatSpellID": 102,
                "duration": 0,
                "name": "Forest's Touch",
                "hasThornsEffect": false,
                "cooldown": 2
            }],
            "role": 1,
            "name": "Groonoomcrooek",
            "boardIndex": 0,
            "health": 1125,
            "level": 35,
            "maxHealth": 1125,
            "attack": 180
        },```
 So first spell id would be 102?

**Comment by zealvurte** [comment]
Nope, you're right, sorry. The followers don't have their auto attack as their first spell, or anywhere.

Groonoomcrooek doesn't need an override, because the role of 1 will assign 11 anyway.
Chachi the artiste does need an override, because the role of 4 will incorrect assign 15.

**Comment by Gaboros** [comment]
> Groonoomcrooek doesn't need an override, because the role of 1 will assign 11 anyway.
> Chachi the Artiste does need an override, because the role of 4 will incorrectly assign 15.

Ah forgot the role. Yes this seems right!
