### ISSUE TITLE
wrong auto attck style

### ISSUE THREAD

**Issue by LostTemple1990** [Gaboros/VenturePlan#46]
here are some wrong auto attack style i found
missionId = 2301  enemy index = 9
missionId = 2303  enemy index = 9,10,11,12
missionId = 2304  enemy index = 5,6,7,8,9,10,11,12
missionId = 2307  enemy index = 9,10,11,12

**Comment by zealvurte** [comment]
These should have all been fixed to be 11 with #38 in 5.3 already, but please use 5.4 to check again if you encounter the same issue.
