### ISSUE TITLE
Incorrect predictionCorrect value, and redundant initial serialize

### ISSUE THREAD

**Issue by zealvurte** [Gaboros/VenturePlan#49]
The reports are being serialized twice, with the first one when `st` is initialised being wasted.

Also `predictionCorrect` is using the wrong return value from `isNovelLog()`; it's currently only reporting if the outcome (win/loss) is different, not if the sim was correct.

Collector.lua:177-178
Change:
```lua
		local st, novel, nok, om = serialize(cr), isNovelLog(cr, checkpoints)
		cr.predictionCorrect = om
```
To:
```lua
		local novel, nok, om, st = isNovelLog(cr, checkpoints)
		cr.predictionCorrect = not novel
```

**Comment by Gaboros** [comment]
Sooo novel means if the prediction was correct? This wasn't clear at all for me, thanks!

**Comment by zealvurte** [comment]
`novel` in this case means either one of these:
- There was an error in the pcall
- There was a mismatch in the number of log and sim checkpoints (e.g. one logged more or less turns than the other)
- There was a mismatch between a log and sim checkpoint (e.g. health differed)

`om` on the other hand just indicates if there is a mismatch between the outcome between the log and sim (e.g. one said win and the other loss)
