### ISSUE TITLE
Darkness from above (347) has raw damage rather than multiplier?

### ISSUE THREAD

**Issue by dphennessy** [Gaboros/VenturePlan#5]
https://github.com/Gaboros/Venture-Plan-Missions/blob/d863947bf1c6317da221447d76611a73c9a72e1e/vs-spells.lua#L385

![screenshot](https://i.imgur.com/xlG0bXo.png)

Would the modifier not be 1 in this case? I don't see where the 204 is from.

**Comment by dphennessy** [comment]
Scratch that, the modifier should be 100 I think?

**Comment by dphennessy** [comment]
Emptied mug is fine since the multiplier is 150 for both cases 
(91 / 61) * 100 ~= 150
(88 / 59) * 100 ~= 150
So when venture plan is calculating the dmg it looks at the attack power, then adds the multiplier (i.e. 61 attack power increased by 150% is 91 dmg)

In the case for Darkness from Above it seems the attack power is just 1:1 with the spell damage, so it doesn't need a modifier (aka it should be damageATK = 100)  i think

**Comment by Gaboros** [comment]
Makes sense. Maybe than it's just a simple error on the current code. These are not validated yet. :) 
That is why I started to collect screenshots :)
