### ISSUE TITLE
Add language to the logs

### ISSUE THREAD

**Issue by Gaboros** [Gaboros/VenturePlan#54]
Currently the parser is relies on a lib called apache tika which is amazing but sometimes can not predict correctly if the text is in english. That is why some null for mission names on some views. Would be better to add language to the logs if possible and rely on that.

**Comment by sehra** [comment]
Looks like the language is already in the logs under `meta.lc`.

**Comment by Gaboros** [comment]
Great, then just have to push into the serializer. :)
I didn't checked it, just created the issue to not forget it and went to work. :D
