### ISSUE TITLE
Supporting Fire/Oversight Coefficient Issue

### ISSUE THREAD

**Issue by EvanMichaels** [Gaboros/VenturePlan#7]
Supporting Fire:
> [331]={type="aura", target="all-allies", plusDamageDealtATK=23, duration=3},

This appears to be a 20% coefficient in-game, with 23 as the tooltip. 118 ranged damage converts to a ratio of 19.49, so assuming this is really 20 with a rounded value. 

Additionally, if we compare to Oversight:
> [330]={type="aura", target=4, duration=2, plusDamageDealtATK=25},

I have a mission where both Oversight and Supporting Fire are identical in tooltip value. 
![image](https://user-images.githubusercontent.com/24741480/124947904-3cc1ce00-dfde-11eb-99aa-b21f3eeefd9e.png)
![image](https://user-images.githubusercontent.com/24741480/124947947-45b29f80-dfde-11eb-9926-7c76e4b2aeef.png)

So it seems these both should have the same coefficient of 20?

**Comment by PositiveKoodoo** [comment]
This is already fixed in the newest version, see:

https://github.com/Gaboros/VenturePlan/blob/2884f71839548330029b65e973717e53c52b0127/Addon/vs-spells.lua#L399
and
https://github.com/Gaboros/VenturePlan/blob/e3bdcce5a3d68b5f40743ebeca0c954b016e470b/Addon/vs-spells.lua#L400

**Comment by Gaboros** [comment]
@PositiveKoodoo is Supporting Fire need duration 3? I think not but not sure.
